# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5PMgBVT37pd3ZYHOtNOjtZp2LPo5IXm
"""

!pip install pydub librosa

# Pydub uchun ffmpeg ni o'rnatish
!apt-get install ffmpeg

from pydub import AudioSegment
import matplotlib.pyplot as plt
import numpy as np
import librosa
import librosa.display

# Ovoz faylini yuklab olish (Google Drive yoki boshqa manbadan)
from google.colab import files
uploaded = files.upload()

# Yuklangan ovoz faylini ochish
audio = AudioSegment.from_file("22.mp3")

# Ovoz faylini kesish (0 dan 10 sekundgacha)
audio_segment = audio[:10000]

# Ovoz faylini yangi nom bilan saqlash
audio_segment.export("33.mp3", format="mp3")

# Ovoz faylini yuklash va tahlil qilish (librosa)
audio_data, sr = librosa.load("22.mp3")
plt.figure(figsize=(14, 5))
librosa.display.waveshow(audio_data, sr=sr)
plt.title('Waveform of Audio')
plt.show()

# Spektrogramma chizish
X = librosa.stft(audio_data)
Xdb = librosa.amplitude_to_db(abs(X))

plt.figure(figsize=(14, 5))
librosa.display.specshow(Xdb, sr=sr, x_axis='time', y_axis='hz')
plt.colorbar(format='%+2.0f dB')
plt.title('Spectrogram')
plt.show()